name: MDCB
version: ${mod_version}
main: za.net.hanro50.dischat.paper.DisChat
description: A Discord chat bridge.
author: hanro50
api-version: "1.21.1"
libraries:
  - net.dv8tion:JDA:6.0.0
commands:
  linkme:
    description: Link your Discord and Minecraft Account
    usage: /<command>
    permission: dischat.link
    default: true
